//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entity : DbContext
    {
        public Entity()
            : base("name=Entity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alarm> Alarm { get; set; }
        public virtual DbSet<AmisTask> AmisTask { get; set; }
        public virtual DbSet<AmisTaskType> AmisTaskType { get; set; }
        public virtual DbSet<AmisUser> AmisUser { get; set; }
        public virtual DbSet<AmisUserTask> AmisUserTask { get; set; }
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<Asset> Asset { get; set; }
        public virtual DbSet<AssetEvent> AssetEvent { get; set; }
        public virtual DbSet<AssetModel> AssetModel { get; set; }
        public virtual DbSet<AssetModelService> AssetModelService { get; set; }
        public virtual DbSet<AssetPosition> AssetPosition { get; set; }
        public virtual DbSet<AssetSituation> AssetSituation { get; set; }
        public virtual DbSet<AssetType> AssetType { get; set; }
        public virtual DbSet<AssetUniqueIdentification> AssetUniqueIdentification { get; set; }
        public virtual DbSet<AssignedUnit> AssignedUnit { get; set; }
        public virtual DbSet<Assignment> Assignment { get; set; }
        public virtual DbSet<AuditDocument> AuditDocument { get; set; }
        public virtual DbSet<AuditDocumentItem> AuditDocumentItem { get; set; }
        public virtual DbSet<AxleConfiguration> AxleConfiguration { get; set; }
        public virtual DbSet<BranchOffice> BranchOffice { get; set; }
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<Commune> Commune { get; set; }
        public virtual DbSet<ConfigurationAxleUnitType> ConfigurationAxleUnitType { get; set; }
        public virtual DbSet<ConfigurationUnitType> ConfigurationUnitType { get; set; }
        public virtual DbSet<CostBaseLine> CostBaseLine { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<DepthSetting> DepthSetting { get; set; }
        public virtual DbSet<DispatchDocument> DispatchDocument { get; set; }
        public virtual DbSet<DispatchDocumentItem> DispatchDocumentItem { get; set; }
        public virtual DbSet<DispatchProviderDocument> DispatchProviderDocument { get; set; }
        public virtual DbSet<DispatchProviderDocumentItem> DispatchProviderDocumentItem { get; set; }
        public virtual DbSet<DispatchProviderDocumentState> DispatchProviderDocumentState { get; set; }
        public virtual DbSet<EventAssetType> EventAssetType { get; set; }
        public virtual DbSet<Facility> Facility { get; set; }
        public virtual DbSet<FacilityType> FacilityType { get; set; }
        public virtual DbSet<FireType> FireType { get; set; }
        public virtual DbSet<GlobalCost> GlobalCost { get; set; }
        public virtual DbSet<GlobalCostDetail> GlobalCostDetail { get; set; }
        public virtual DbSet<IndexWegh> IndexWegh { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<Manufacturer> Manufacturer { get; set; }
        public virtual DbSet<MeasurementsTyre> MeasurementsTyre { get; set; }
        public virtual DbSet<MeasurementUnit> MeasurementUnit { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<MemberBranchOffice> MemberBranchOffice { get; set; }
        public virtual DbSet<MemberType> MemberType { get; set; }
        public virtual DbSet<MenuOption> MenuOption { get; set; }
        public virtual DbSet<Operation> Operation { get; set; }
        public virtual DbSet<Origin> Origin { get; set; }
        public virtual DbSet<PageAction> PageAction { get; set; }
        public virtual DbSet<PageLog> PageLog { get; set; }
        public virtual DbSet<PressureSetting> PressureSetting { get; set; }
        public virtual DbSet<ReceptionDocument> ReceptionDocument { get; set; }
        public virtual DbSet<ReceptionDocumentItem> ReceptionDocumentItem { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<RepairType> RepairType { get; set; }
        public virtual DbSet<ScrapType> ScrapType { get; set; }
        public virtual DbSet<SettingBattery> SettingBattery { get; set; }
        public virtual DbSet<SettingCat> SettingCat { get; set; }
        public virtual DbSet<SettingExtinguisher> SettingExtinguisher { get; set; }
        public virtual DbSet<SettingLigthPole> SettingLigthPole { get; set; }
        public virtual DbSet<SettingRadio> SettingRadio { get; set; }
        public virtual DbSet<SettingTyre> SettingTyre { get; set; }
        public virtual DbSet<SituationType> SituationType { get; set; }
        public virtual DbSet<SpeedIndex> SpeedIndex { get; set; }
        public virtual DbSet<SubEventAssetType> SubEventAssetType { get; set; }
        public virtual DbSet<SuspensionType> SuspensionType { get; set; }
        public virtual DbSet<SystemParameter> SystemParameter { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
        public virtual DbSet<TagAssigned> TagAssigned { get; set; }
        public virtual DbSet<TractionType> TractionType { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<UnitAsset> UnitAsset { get; set; }
        public virtual DbSet<UnitRegister> UnitRegister { get; set; }
        public virtual DbSet<UnitType> UnitType { get; set; }
        public virtual DbSet<UserAlarm> UserAlarm { get; set; }
        public virtual DbSet<UserAlarmType> UserAlarmType { get; set; }
        public virtual DbSet<UserMenuOption> UserMenuOption { get; set; }
        public virtual DbSet<Warehouse> Warehouse { get; set; }
    }
}
