//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amis
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmisUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AmisUser()
        {
            this.AmisUserTask = new HashSet<AmisUserTask>();
            this.AuditDocument = new HashSet<AuditDocument>();
            this.PageLog = new HashSet<PageLog>();
            this.UserAlarm = new HashSet<UserAlarm>();
            this.UserMenuOption = new HashSet<UserMenuOption>();
        }
    
        public int AmisUserId { get; set; }
        public int MemberId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Enable { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> DisabledDate { get; set; }
        public string ChangePasswordCode { get; set; }
        public string SecretAnswer { get; set; }
        public string SecretQuestion { get; set; }
        public Nullable<System.DateTime> DisableDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AmisUserTask> AmisUserTask { get; set; }
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditDocument> AuditDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PageLog> PageLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAlarm> UserAlarm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserMenuOption> UserMenuOption { get; set; }
    }
}
