//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amis
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmisTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AmisTask()
        {
            this.AmisUserTask = new HashSet<AmisUserTask>();
        }
    
        public int AmisTaskId { get; set; }
        public int AmisTaskTypeId { get; set; }
        public string AmisTaskName { get; set; }
        public string AmisTaskDescription { get; set; }
    
        public virtual AmisTaskType AmisTaskType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AmisUserTask> AmisUserTask { get; set; }
    }
}
