//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amis
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmisUserTask
    {
        public int AmisUserTaskId { get; set; }
        public int AmisTaskId { get; set; }
        public string AmisUserTaskName { get; set; }
        public string AmisUserTaskDescription { get; set; }
        public string AmisUserTaskActionTaken { get; set; }
        public string AmisUserTaskDone { get; set; }
        public System.DateTime AmisUserTaskStartDate { get; set; }
        public Nullable<System.DateTime> AmisUserTaskFinishDate { get; set; }
        public int AmisUserId { get; set; }
    
        public virtual AmisTask AmisTask { get; set; }
        public virtual AmisUser AmisUser { get; set; }
    }
}
