//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amis
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetEvent
    {
        public int AssetEventId { get; set; }
        public int AssetId { get; set; }
        public int SubEventAssetTypeId { get; set; }
        public Nullable<int> MeasurementUnitId { get; set; }
        public Nullable<int> AssetPositionId { get; set; }
        public Nullable<int> AsignmentId { get; set; }
        public Nullable<int> AssetSituationId { get; set; }
        public int AssetEventMemberId { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> AssetUniqueIdentificationId { get; set; }
        public System.DateTime AssetEventDate { get; set; }
        public Nullable<decimal> AssetEventCost { get; set; }
        public Nullable<decimal> MeasurementAsset { get; set; }
        public Nullable<int> MeasurementKm { get; set; }
        public Nullable<decimal> StartPressureMeasurement { get; set; }
        public Nullable<decimal> FinishPressureMeasurement { get; set; }
        public Nullable<decimal> MeasurementTireTreadDepth1 { get; set; }
        public Nullable<decimal> MeasurementTireTreadDepth2 { get; set; }
        public Nullable<decimal> MeasurementTireTreadDepth3 { get; set; }
        public Nullable<decimal> MeasurementTireTreadDepth4 { get; set; }
        public Nullable<decimal> MeasurementTireTreadDepth5 { get; set; }
        public Nullable<decimal> MeasurementTireTreadDepth6 { get; set; }
        public Nullable<decimal> MeasurementTireTreadDepth7 { get; set; }
        public Nullable<decimal> MeasurementTireTreadDepth8 { get; set; }
        public Nullable<decimal> MeasurementTireTreadDepth9 { get; set; }
        public Nullable<decimal> MeasurementTireTreadDepth10 { get; set; }
        public Nullable<int> ExecutingUserId { get; set; }
        public Nullable<int> AuthorizingUserId { get; set; }
        public string IsGood { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual AssetPosition AssetPosition { get; set; }
        public virtual AssetSituation AssetSituation { get; set; }
        public virtual AssetUniqueIdentification AssetUniqueIdentification { get; set; }
        public virtual Assignment Assignment { get; set; }
        public virtual Facility Facility { get; set; }
        public virtual MeasurementUnit MeasurementUnit { get; set; }
        public virtual Member Member { get; set; }
        public virtual SubEventAssetType SubEventAssetType { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
