//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assignment()
        {
            this.AssetEvent = new HashSet<AssetEvent>();
        }
    
        public int AssignmentId { get; set; }
        public int OperationId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public System.DateTime AssignmentDate { get; set; }
        public Nullable<System.DateTime> EndAssignmentDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetEvent> AssetEvent { get; set; }
        public virtual Operation Operation { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
