//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amis
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignedUnit
    {
        public int AssignedUnitId { get; set; }
        public int UnitParentId { get; set; }
        public Nullable<System.DateTime> UnsignedDate { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
    
        public virtual Unit Unit { get; set; }
    }
}
