//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amis
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AuditDocument()
        {
            this.AuditDocumentItem = new HashSet<AuditDocumentItem>();
        }
    
        public int AuditDocumentId { get; set; }
        public int FacilityId { get; set; }
        public Nullable<int> AmisUserId { get; set; }
        public System.DateTime AuditDocumentDate { get; set; }
    
        public virtual AmisUser AmisUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditDocumentItem> AuditDocumentItem { get; set; }
        public virtual Facility Facility { get; set; }
    }
}
