//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amis
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigurationUnitType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConfigurationUnitType()
        {
            this.ConfigurationAxleUnitType = new HashSet<ConfigurationAxleUnitType>();
            this.UnitRegister = new HashSet<UnitRegister>();
        }
    
        public int ConfigurationUnitTypeId { get; set; }
        public int UnitTypeId { get; set; }
        public int TractionTypeId { get; set; }
        public string ConfigurationUnitTypeName { get; set; }
        public string ConfigurationUnitTypeAbr { get; set; }
        public string Path { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfigurationAxleUnitType> ConfigurationAxleUnitType { get; set; }
        public virtual TractionType TractionType { get; set; }
        public virtual UnitType UnitType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitRegister> UnitRegister { get; set; }
    }
}
