//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amis
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigurationAxleUnitType
    {
        public int ConfigurationUnitTypeId { get; set; }
        public int AxleConfigurationId { get; set; }
        public int ConfigurationAxleUnitTypeid { get; set; }
        public int Position { get; set; }
    
        public virtual AxleConfiguration AxleConfiguration { get; set; }
        public virtual ConfigurationUnitType ConfigurationUnitType { get; set; }
    }
}
