//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amis
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostBaseLine
    {
        public int CostBaseLineId { get; set; }
        public decimal ThirdCost { get; set; }
        public decimal RetreadingCost { get; set; }
        public decimal NewCost { get; set; }
        public decimal FieldCost { get; set; }
        public decimal FinalDisposition { get; set; }
        public decimal ShellCost { get; set; }
        public decimal CostBaseLineYear { get; set; }
    }
}
