//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amis
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepthSetting
    {
        public int DepthSettingId { get; set; }
        public int ApplicationId { get; set; }
        public int AssetModelId { get; set; }
        public decimal ScrapDepth { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual AssetModel AssetModel { get; set; }
    }
}
