//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amis
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatchProviderDocumentItem
    {
        public int DispatchProviderDocumentItemId { get; set; }
        public int DispatchProviderDocumentId { get; set; }
        public int AssetUniqueIdentificationId { get; set; }
        public int DispatchProviderDocumentStateId { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public int DeclaratedAmount { get; set; }
        public int ReceptionAmount { get; set; }
        public decimal ItemCost { get; set; }
        public int ManufacturerYear { get; set; }
        public int AssignedAmount { get; set; }
        public string Observation { get; set; }
        public string Dot { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual AssetUniqueIdentification AssetUniqueIdentification { get; set; }
        public virtual DispatchProviderDocument DispatchProviderDocument { get; set; }
        public virtual DispatchProviderDocumentState DispatchProviderDocumentState { get; set; }
    }
}
