//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amis
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatchProviderDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DispatchProviderDocument()
        {
            this.Asset = new HashSet<Asset>();
            this.DispatchProviderDocumentItem = new HashSet<DispatchProviderDocumentItem>();
        }
    
        public int DispatchProviderDocumentId { get; set; }
        public int FacilityId { get; set; }
        public int DispatchProviderDocumentStateId { get; set; }
        public int ProviderMemberId { get; set; }
        public System.DateTime DispatchDate { get; set; }
        public int DocumentNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset> Asset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DispatchProviderDocumentItem> DispatchProviderDocumentItem { get; set; }
        public virtual DispatchProviderDocumentState DispatchProviderDocumentState { get; set; }
        public virtual Facility Facility { get; set; }
        public virtual Member Member { get; set; }
    }
}
