//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amis
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatchProviderDocumentState
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DispatchProviderDocumentState()
        {
            this.DispatchProviderDocument = new HashSet<DispatchProviderDocument>();
            this.DispatchProviderDocumentItem = new HashSet<DispatchProviderDocumentItem>();
        }
    
        public int DispatchProviderDocumentStateId { get; set; }
        public string DispatchProviderDocumentStateName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DispatchProviderDocument> DispatchProviderDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DispatchProviderDocumentItem> DispatchProviderDocumentItem { get; set; }
    }
}
