//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amis
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalCostDetail
    {
        public int GlobalCostDetailId { get; set; }
        public int GlobalCostId { get; set; }
        public System.DateTime Month { get; set; }
        public decimal Cost { get; set; }
        public int CountUnit { get; set; }
    
        public virtual GlobalCost GlobalCost { get; set; }
    }
}
