//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amis
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuOption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuOption()
        {
            this.MenuOption1 = new HashSet<MenuOption>();
            this.PageLog = new HashSet<PageLog>();
            this.UserMenuOption = new HashSet<UserMenuOption>();
        }
    
        public int MenuOptionId { get; set; }
        public Nullable<int> ParentMenuOptionId { get; set; }
        public string Name { get; set; }
        public string PageURL { get; set; }
        public string WindowType { get; set; }
        public string CreatePermission { get; set; }
        public string ReadPermission { get; set; }
        public string UpdatePermission { get; set; }
        public string DeletePermission { get; set; }
        public string FindPermission { get; set; }
        public string ExecutePermission { get; set; }
        public string ChangePermission { get; set; }
        public string GenerateReport { get; set; }
        public string AuthorizePermission { get; set; }
        public string Action1 { get; set; }
        public string NameAction1 { get; set; }
        public string Action2 { get; set; }
        public string NameAction2 { get; set; }
        public string Action3 { get; set; }
        public string NameAction3 { get; set; }
        public string Action4 { get; set; }
        public string NameAction4 { get; set; }
        public string Action5 { get; set; }
        public string NameAction5 { get; set; }
        public string Action6 { get; set; }
        public string NameAction6 { get; set; }
        public string Action7 { get; set; }
        public string NameAction7 { get; set; }
        public string Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuOption> MenuOption1 { get; set; }
        public virtual MenuOption MenuOption2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PageLog> PageLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserMenuOption> UserMenuOption { get; set; }
    }
}
