//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amis
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageLog
    {
        public int PageLogId { get; set; }
        public int MenuOptionId { get; set; }
        public int PageActionId { get; set; }
        public Nullable<int> AmisUserId { get; set; }
        public string Description { get; set; }
        public System.DateTime ActionDateTime { get; set; }
    
        public virtual AmisUser AmisUser { get; set; }
        public virtual MenuOption MenuOption { get; set; }
        public virtual PageAction PageAction { get; set; }
    }
}
