//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amis
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceptionDocumentItem
    {
        public int ReceptionDocumentItemId { get; set; }
        public int ReceptionDocumentId { get; set; }
        public int AssetId { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual ReceptionDocument ReceptionDocument { get; set; }
    }
}
