//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amis
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceptionDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReceptionDocument()
        {
            this.ReceptionDocumentItem = new HashSet<ReceptionDocumentItem>();
        }
    
        public int ReceptionDocumentId { get; set; }
        public int ReceptionFacilityId { get; set; }
        public System.DateTime ReceptionDate { get; set; }
        public int ReceptionDocumentNumber { get; set; }
        public decimal Cost { get; set; }
    
        public virtual Facility Facility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceptionDocumentItem> ReceptionDocumentItem { get; set; }
    }
}
