//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amis
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingTyre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SettingTyre()
        {
            this.AssetUniqueIdentification = new HashSet<AssetUniqueIdentification>();
        }
    
        public int SettingTyreId { get; set; }
        public int MeasurementsTyreId { get; set; }
        public int IndexWeghId { get; set; }
        public int SpeedIndexId { get; set; }
        public string Original { get; set; }
        public int DepthNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetUniqueIdentification> AssetUniqueIdentification { get; set; }
        public virtual IndexWegh IndexWegh { get; set; }
        public virtual MeasurementsTyre MeasurementsTyre { get; set; }
        public virtual SpeedIndex SpeedIndex { get; set; }
    }
}
