//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amis
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingExtinguisher
    {
        public int SettingExtinguisherId { get; set; }
        public int AssetModelId { get; set; }
        public int FireTypeId { get; set; }
        public int FireSize { get; set; }
        public System.DateTime EndLifeDate { get; set; }
    
        public virtual AssetModel AssetModel { get; set; }
        public virtual FireType FireType { get; set; }
    }
}
