//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amis
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitRegister
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnitRegister()
        {
            this.Unit = new HashSet<Unit>();
        }
    
        public int UnitRegisterId { get; set; }
        public int UnitTypeId { get; set; }
        public int UnitTypeConfigurationId { get; set; }
        public int SuspensionTypeId { get; set; }
        public int UnitOwnerMemberId { get; set; }
        public int KilometersOfTravel { get; set; }
        public System.DateTime UnitPurchaseDate { get; set; }
        public string UnitName { get; set; }
        public string PatentNumber { get; set; }
        public int UnitManufacturingYear { get; set; }
        public string NewOrUsed { get; set; }
        public decimal UnitTara { get; set; }
        public string Vin { get; set; }
        public string InternalNumber { get; set; }
        public Nullable<System.DateTime> NextDrivingLicenseDate { get; set; }
        public Nullable<System.DateTime> NextTechnicalReviewDate { get; set; }
        public Nullable<System.DateTime> NextQualificationDate { get; set; }
    
        public virtual ConfigurationUnitType ConfigurationUnitType { get; set; }
        public virtual Member Member { get; set; }
        public virtual SuspensionType SuspensionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unit> Unit { get; set; }
        public virtual UnitType UnitType { get; set; }
    }
}
