//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amis
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitAsset
    {
        public int UnitAssetId { get; set; }
        public int AssetId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> AssetPositionId { get; set; }
        public System.DateTime AssignedDate { get; set; }
        public Nullable<System.DateTime> UnassignedDate { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual AssetPosition AssetPosition { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
