//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amis
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAlarm
    {
        public int UserAlarmId { get; set; }
        public int AmisUserId { get; set; }
        public int AlarmId { get; set; }
        public int UserAlarmTypeId { get; set; }
    
        public virtual Alarm Alarm { get; set; }
        public virtual AmisUser AmisUser { get; set; }
        public virtual UserAlarmType UserAlarmType { get; set; }
    }
}
