//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amis
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMenuOption
    {
        public int UserMenuOptionId { get; set; }
        public int MenuOptionId { get; set; }
        public Nullable<int> AmisUserId { get; set; }
        public string CanCreate { get; set; }
        public string CanRead { get; set; }
        public string CanUpdate { get; set; }
        public string CanDelete { get; set; }
        public string CanFind { get; set; }
        public string CanExecute { get; set; }
        public string CanChange { get; set; }
        public string CanAuthorize { get; set; }
        public string CanDoAction1 { get; set; }
        public string CanDoAction2 { get; set; }
        public string CanDoAction3 { get; set; }
        public string CanDoAction4 { get; set; }
        public string CanDoAction5 { get; set; }
        public string CanDoAction6 { get; set; }
        public string CanDoAction7 { get; set; }
        public string CanGenerateReport { get; set; }
    
        public virtual AmisUser AmisUser { get; set; }
        public virtual MenuOption MenuOption { get; set; }
    }
}
